---
name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dev requirements
        run: sudo apt install python3-bashate shellcheck yamllint
      - name: Check code
        run: make check
